import { Skill, Employee, GrowthPlan, SkillRating } from './types';

export const SKILLS: Skill[] = [
  { id: 's1', name: 'Selenium', category: 'Tool' },
  { id: 's2', name: 'Appium', category: 'Tool' },
  { id: 's3', name: 'JMeter', category: 'Tool' },
  { id: 's4', name: 'Postman', category: 'Tool' },
  { id: 's5', name: 'JIRA', category: 'Tool' },
  { id: 's6', name: 'TestRail', category: 'Tool' },
  { id: 's7', name: 'Python', category: 'Technology' },
  { id: 's8', name: 'Java', category: 'Technology' },
  { id: 's9', name: 'JavaScript', category: 'Technology' },
  { id: 's10', name: 'TypeScript', category: 'Technology' },
  { id: 's11', name: 'C#', category: 'Technology' },
  { id: 's12', name: 'SQL', category: 'Technology' },
  { id: 's13', name: 'API Testing', category: 'Application' },
  { id: 's14', name: 'Mobile Testing', category: 'Application' },
  { id: 's15', name: 'Performance Testing', category: 'Application' },
  { id: 's16', name: 'Security Testing', category: 'Application' },
  { id: 's17', name: 'Database Testing', category: 'Application' },
  { id: 's18', name: 'Banking', category: 'Domain' },
  { id: 's19', name: 'Healthcare', category: 'Domain' },
  { id: 's20', name: 'E-Commerce', category: 'Domain' },
  { id: 's21', name: 'Insurance', category: 'Domain' },
  { id: 's22', name: 'Telecom', category: 'Domain' },
  { id: 's23', name: 'Manual Testing', category: 'TestingType' },
  { id: 's24', name: 'Automation Testing', category: 'TestingType' },
  { id: 's25', name: 'Regression Testing', category: 'TestingType' },
  { id: 's26', name: 'UAT', category: 'TestingType' },
  { id: 's27', name: 'Git', category: 'DevOps' },
  { id: 's28', name: 'Jenkins', category: 'DevOps' },
  { id: 's29', name: 'Docker', category: 'DevOps' },
  { id: 's30', name: 'Azure DevOps', category: 'DevOps' },
  { id: 's31', name: 'ChatGPT/Prompt Engineering', category: 'AI' },
  { id: 's32', name: 'AI Test Automation', category: 'AI' },
];

export const RESUME_DETECTED_SKILLS: SkillRating[] = [
  { skillId: 's1', selfRating: 2, managerRating: null, validated: false },
  { skillId: 's7', selfRating: 2, managerRating: null, validated: false },
  { skillId: 's13', selfRating: 2, managerRating: null, validated: false },
  { skillId: 's18', selfRating: 1, managerRating: null, validated: false },
  { skillId: 's23', selfRating: 3, managerRating: null, validated: false },
  { skillId: 's27', selfRating: 2, managerRating: null, validated: false },
  { skillId: 's31', selfRating: 1, managerRating: null, validated: false },
  { skillId: 's8', selfRating: 1, managerRating: null, validated: false },
];

const makeSkills = (overrides: Partial<SkillRating>[] = []): SkillRating[] => {
  const base: SkillRating[] = SKILLS.map(s => ({
    skillId: s.id,
    selfRating: 0 as const,
    managerRating: null,
    validated: false,
  }));
  overrides.forEach(o => {
    const idx = base.findIndex(b => b.skillId === o.skillId);
    if (idx >= 0) Object.assign(base[idx], o);
  });
  return base;
};

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: 'emp1',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@zensar.com',
    designation: 'Senior Test Engineer',
    department: 'Quality Engineering',
    yearsIT: 5,
    yearsZensar: 3,
    primarySkill: 'Selenium',
    primaryDomain: 'Banking',
    skills: makeSkills([
      { skillId: 's1', selfRating: 3, managerRating: 3, validated: true },
      { skillId: 's7', selfRating: 2, managerRating: 2, validated: true },
      { skillId: 's8', selfRating: 2, managerRating: 2, validated: true },
      { skillId: 's13', selfRating: 3, managerRating: 2, validated: true },
      { skillId: 's18', selfRating: 2, managerRating: 2, validated: true },
      { skillId: 's23', selfRating: 3, managerRating: 3, validated: true },
      { skillId: 's24', selfRating: 3, managerRating: 3, validated: true },
      { skillId: 's27', selfRating: 2, managerRating: 2, validated: true },
      { skillId: 's31', selfRating: 1, managerRating: 1, validated: true },
    ]),
    resumeUploaded: true,
    overallCapability: 72,
  },
  {
    id: 'emp2',
    name: 'Priya Patel',
    email: 'priya.patel@zensar.com',
    designation: 'Test Lead',
    department: 'Quality Engineering',
    yearsIT: 8,
    yearsZensar: 4,
    primarySkill: 'API Testing',
    primaryDomain: 'Healthcare',
    skills: makeSkills([
      { skillId: 's1', selfRating: 2, managerRating: 2, validated: true },
      { skillId: 's4', selfRating: 3, managerRating: 3, validated: true },
      { skillId: 's7', selfRating: 3, managerRating: 3, validated: true },
      { skillId: 's9', selfRating: 2, managerRating: 2, validated: true },
      { skillId: 's12', selfRating: 3, managerRating: 3, validated: true },
      { skillId: 's13', selfRating: 3, managerRating: 3, validated: true },
      { skillId: 's15', selfRating: 2, managerRating: 2, validated: true },
      { skillId: 's19', selfRating: 3, managerRating: 3, validated: true },
      { skillId: 's23', selfRating: 3, managerRating: 3, validated: true },
      { skillId: 's27', selfRating: 3, managerRating: 3, validated: true },
      { skillId: 's28', selfRating: 2, managerRating: 2, validated: true },
      { skillId: 's31', selfRating: 2, managerRating: 2, validated: true },
    ]),
    resumeUploaded: true,
    overallCapability: 85,
  },
  {
    id: 'emp3',
    name: 'Amit Kumar',
    email: 'amit.kumar@zensar.com',
    designation: 'Junior Test Engineer',
    department: 'Quality Engineering',
    yearsIT: 2,
    yearsZensar: 1,
    primarySkill: 'Manual Testing',
    primaryDomain: 'E-Commerce',
    skills: makeSkills([
      { skillId: 's5', selfRating: 2, managerRating: 1, validated: true },
      { skillId: 's7', selfRating: 1, managerRating: 1, validated: true },
      { skillId: 's12', selfRating: 1, managerRating: 1, validated: true },
      { skillId: 's20', selfRating: 2, managerRating: 2, validated: true },
      { skillId: 's23', selfRating: 2, managerRating: 2, validated: true },
      { skillId: 's25', selfRating: 2, managerRating: 2, validated: true },
    ]),
    resumeUploaded: true,
    overallCapability: 38,
  },
  {
    id: 'emp4',
    name: 'Sneha Desai',
    email: 'sneha.desai@zensar.com',
    designation: 'Performance Test Engineer',
    department: 'Quality Engineering',
    yearsIT: 6,
    yearsZensar: 2,
    primarySkill: 'JMeter',
    primaryDomain: 'Telecom',
    skills: makeSkills([
      { skillId: 's3', selfRating: 3, managerRating: 3, validated: true },
      { skillId: 's7', selfRating: 2, managerRating: 2, validated: true },
      { skillId: 's12', selfRating: 2, managerRating: 2, validated: true },
      { skillId: 's15', selfRating: 3, managerRating: 3, validated: true },
      { skillId: 's22', selfRating: 2, managerRating: 2, validated: true },
      { skillId: 's27', selfRating: 2, managerRating: 2, validated: true },
      { skillId: 's29', selfRating: 2, managerRating: 1, validated: true },
      { skillId: 's30', selfRating: 2, managerRating: 2, validated: true },
    ]),
    resumeUploaded: true,
    overallCapability: 65,
  },
  {
    id: 'emp5',
    name: 'Vikram Singh',
    email: 'vikram.singh@zensar.com',
    designation: 'Automation Architect',
    department: 'Quality Engineering',
    yearsIT: 10,
    yearsZensar: 5,
    primarySkill: 'Selenium',
    primaryDomain: 'Insurance',
    skills: makeSkills([
      { skillId: 's1', selfRating: 3, managerRating: 3, validated: true },
      { skillId: 's2', selfRating: 3, managerRating: 3, validated: true },
      { skillId: 's7', selfRating: 3, managerRating: 3, validated: true },
      { skillId: 's8', selfRating: 3, managerRating: 3, validated: true },
      { skillId: 's9', selfRating: 2, managerRating: 2, validated: true },
      { skillId: 's13', selfRating: 3, managerRating: 3, validated: true },
      { skillId: 's16', selfRating: 2, managerRating: 2, validated: true },
      { skillId: 's21', selfRating: 3, managerRating: 3, validated: true },
      { skillId: 's24', selfRating: 3, managerRating: 3, validated: true },
      { skillId: 's27', selfRating: 3, managerRating: 3, validated: true },
      { skillId: 's28', selfRating: 3, managerRating: 3, validated: true },
      { skillId: 's29', selfRating: 3, managerRating: 2, validated: true },
      { skillId: 's30', selfRating: 3, managerRating: 3, validated: true },
      { skillId: 's31', selfRating: 2, managerRating: 2, validated: true },
      { skillId: 's32', selfRating: 2, managerRating: 2, validated: true },
    ]),
    resumeUploaded: true,
    overallCapability: 92,
  },
];

export const MOCK_GROWTH_PLANS: GrowthPlan[] = [
  { id: 'gp1', employeeId: 'emp1', skillId: 's7', currentLevel: 2, targetLevel: 3, targetDate: '2025-06-30', progress: 60, status: 'in-progress', actions: ['Complete advanced Python course', 'Build pytest framework', 'Mentor junior team member'] },
  { id: 'gp2', employeeId: 'emp1', skillId: 's15', currentLevel: 0, targetLevel: 2, targetDate: '2025-09-30', progress: 20, status: 'in-progress', actions: ['JMeter fundamentals', 'Performance test planning', 'Run 3 load tests'] },
  { id: 'gp3', employeeId: 'emp3', skillId: 's1', currentLevel: 0, targetLevel: 2, targetDate: '2025-08-31', progress: 10, status: 'not-started', actions: ['Selenium WebDriver basics', 'Page Object Model', 'Framework development'] },
  { id: 'gp4', employeeId: 'emp3', skillId: 's7', currentLevel: 1, targetLevel: 2, targetDate: '2025-07-31', progress: 40, status: 'in-progress', actions: ['Python intermediate course', 'Automation scripting practice'] },
  { id: 'gp5', employeeId: 'emp4', skillId: 's29', currentLevel: 2, targetLevel: 3, targetDate: '2025-05-31', progress: 80, status: 'in-progress', actions: ['Docker advanced networking', 'Container orchestration', 'CI/CD pipeline setup'] },
];
